=== hirmerpl/SitOPT/situation_template_mapping/situation_template_draft01.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!-- XML Schema definition of a SituationTemplate to observe sensor data and detects occurring situations -->
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	
	<!-- root -->
	<xs:element name="SituationTemplate" type="tSituationTemplate"/>
	
	<!-- TODO: set maxOccurs="unbounded", a situation template could contain more than one situation -->
	<xs:complexType name="tSituationTemplate">
		<xs:sequence>
			<xs:element name="Situation" type="tSituation" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" use="required"/>
		<xs:attribute name="name" type="xs:string"/>
	</xs:complexType>
	
	<xs:complexType name="tSituation">
		<xs:sequence>
			<xs:element name="logicNode" type="tLogicNode" maxOccurs="unbounded"/>
			<xs:element name="node" type="tNode" maxOccurs="unbounded"/>
			<xs:element name="sensorNode" type="tSensorNode" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" use="required"/>
		<xs:attribute name="name" type="xs:string"/>
	</xs:complexType>
	
	<xs:complexType name="tLogicNode">
		<xs:sequence>
			<xs:element name="parent" type="tParent" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="type">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="or|and"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" use="required"/>
		<xs:attribute name="name" type="xs:string"/>
	</xs:complexType>
	
	<!-- TODO (?): set use="required" on parent element of sensor nodes, each sensor should be processed -->
	<xs:complexType name="tSensorNode">
		<xs:sequence>
			<xs:element name="parent" type="tParent" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" use="required"/>
		<xs:attribute name="name" type="xs:string"/>
	</xs:complexType>
	
	<!-- main processing node. TODO: handle sub-situations -->
	<xs:complexType name="tNode">
		<xs:sequence>
			<xs:element name="type" type="xs:string"/> 
			<xs:element name="measureName" type="xs:string"/>
			<xs:element name="opType" type="xs:string" maxOccurs="1" minOccurs="1"/>
			<xs:element name="condValue">
				<xs:complexType>
					<xs:attribute name="value" type="xs:string"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="parent" type="tParent" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" use="required"/>
		<xs:attribute name="name" type="xs:string"/>
	</xs:complexType>

	<xs:complexType name="tParent">
		<xs:attribute name="parentID" type="xs:IDREF"/>
	</xs:complexType>

</xs:schema>

=== hirmerpl/SitOPT/situation_template_mapping/test/situation_template_draft02.xml
<?xml version="1.0" encoding="UTF-8"?>
<SituationTemplate id="A0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="situation_template_draft01.xsd"
	name="SystemObservation">
	<Situation id="A1" name="SystemFailure">
		<logicNode id="A2" name="AND (CPU and RAM sensor)">
			<parent parentID="A3"/>
			<type>and</type>
		</logicNode>
		<logicNode id="A3" name="OR (rootNode)">
			<type>or</type>
		</logicNode>
		<node id="A4" name="CPU high load">
			<type>type</type>
			<measureName>measureName</measureName>
			<opType>greaterThan</opType>
			<condValue value="70"/>
			<parent parentID="A2"/>
		</node>
		<node id="A8" name="RAM full">
			<type>type</type>
			<measureName>measureName</measureName>
			<opType>greaterThan</opType>
			<condValue value="90"/>
			<parent parentID="A2"/>
		</node>
		<sensorNode id="A5" name="memorySensor">
			<parent parentID="A8"></parent>
		</sensorNode>
		<sensorNode id="A6" name="cpuSensor">
			<parent parentID="A4"></parent>
		</sensorNode>
		<sensorNode id="A7" name ="watchdogSensor">
			<parent parentID="A3"/>
		</sensorNode>
	</Situation>
</SituationTemplate>

=== hirmerpl/SitOPT/situation_template_mapping/situation_template_draft01.xml
<?xml version="1.0" encoding="UTF-8"?>
<SituationTemplate id="A0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="situation_template_draft01.xsd"
	name="SystemObservation">
	<Situation id="A1" name="SystemFailure">
		<logicNode id="A3" name="combine Sensors">
			<type>or</type>
		</logicNode>
		<node id="A4" name="% CPU load">
			<type>type</type>
			<measureName>measureName</measureName>
			<opType>greaterThan</opType>
			<condValues>
				<val>70</val>
			</condValues>
			<parent parentID="A3"/>
		</node>
		<node id="A8" name="MB RAM free">
			<type>type</type>
			<measureName>measureName</measureName>
			<opType>lowerThan</opType>
			<condValues>
				<val>10</val>
			</condValues>
			<parent parentID="A3"/>
		</node>
		<node id="A9">
			<type>type</type>
			<measureName>measureName</measureName>
			<opType>notStatusCode</opType>
			<condValues>
				<val>200</val>
			</condValues>
			<parent parentID="A3"></parent>
		</node>
		<sensorNode id="A5" name="memorySensor">
			<parent parentID="A8"></parent>
		</sensorNode>
		<sensorNode id="A6" name="cpuSensor">
			<parent parentID="A4"></parent>
		</sensorNode>
		<sensorNode id="A7" name ="watchdogSensor">
			<parent parentID="A9"/>
		</sensorNode>
	</Situation>
</SituationTemplate>
