=== hirmerpl/SitOPT/schema/situation_template_draft01.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!-- XML Schema definition of a SituationTemplate to observe sensor data and detects occurring situations -->
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	
	<!-- root -->
	<xs:element name="SituationTemplate" type="tSituationTemplate"/>
	
	<!-- TODO: set maxOccurs="unbounded", a situation template could contain more than one situation -->
	<xs:complexType name="tSituationTemplate">
		<xs:sequence>
			<xs:element name="Situation" type="tSituation" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" use="required"/>
	</xs:complexType>
	
	<xs:complexType name="tSituation">
		<xs:sequence>
			<xs:element name="logicNode" type="tLogicNode"/>
			<xs:element name="node" type="tNode" maxOccurs="unbounded"/>
			<xs:element name="sensorNode" type="tSensorNode" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" use="required"/>
	</xs:complexType>
	
	<xs:complexType name="tLogicNode">
		<xs:sequence>
			<xs:element name="type">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="or|and"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" use="required"/>
	</xs:complexType>
	
	<!-- TODO (?): set use="required" on parent element of sensor nodes, each sensor should be processed -->
	<xs:complexType name="tSensorNode">
		<xs:sequence>
			<xs:element name="parent" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="name" type="xs:string"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" use="required"/>
	</xs:complexType>
	
	<!-- main processing node. TODO: handle sub-situations -->
	<xs:complexType name="tNode">
		<xs:sequence>
			<xs:element name="type" type="xs:string"/> 
			<xs:element name="measureName" type="xs:string"/>
			<xs:element name="opType" type="xs:string" maxOccurs="1" minOccurs="1"/>
			<xs:element name="condValues" type="tCondValues"/>
			<xs:element name="parent" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" use="required"/>
	</xs:complexType>

	<!-- TODO: change to attribute "val" of element condValues-->
	<xs:complexType name ="tCondValues">
		<xs:sequence>
			<xs:element name="val" type="xs:integer"/>		
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== hirmerpl/SitOPT/schema/situation_template_draft01.xml
<?xml version="1.0" encoding="UTF-8"?>
<SituationTemplate id="A0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="situation_template_draft01.xsd"
	name="SystemObservation">
	<Situation id="A1" name="SystemFailure">
		<logicNode id="A2">
			<parent parentID="A3"/>
			<name>sensorCombinationNode</name>
			<type>and</type>
		</logicNode>
		<logicNode id="A3">
			<name>SituationRootNode</name>
			<type>or</type>
		</logicNode>
		<node id="A4">
			<type>type</type>
			<measureName>measureName</measureName>
			<opType>greaterThan</opType>
			<condValues>
				<val>70</val>
			</condValues>
			<parent parentID="A2"></parent>
		</node>
		<node id="A8">
			<type>type</type>
			<measureName>measureName</measureName>
			<opType>greaterThan</opType>
			<condValues>
				<val>90</val>
			</condValues>
			<parent parentID="A2"></parent>
		</node>
		<sensorNode id="A5">
			<parent parentID="A8"></parent>
			<name>memorySensor</name>
		</sensorNode>
		<sensorNode id="A6">
			<parent parentID="A8"></parent>
			<name>cpuSensor</name>
		</sensorNode>
		<sensorNode id="A7">
			<parent parentID="A3"></parent>
			<name>watchdogSensor</name>
		</sensorNode>
	</Situation>
</SituationTemplate>
